[package]
name = "getmac-rs"
version = "0.1.0"
authors = ["wangsijie <wangsijie@bytedance.com>"]

[dependencies]
error-chain = "0.12.0"
regex = "1.0.2"
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.5", features = ["winbase"] }